/**
 * Command identifiers for the Angular VSCode extension.
 * All command IDs are short identifiers without the extension prefix.
 * The prefix must be applied at usage time: `${EXTENSION_ID}.${CommandIds.X}`
 */
export enum CommandIds {
  ChangeWorkspace = 'changeWorkspace',
  FileClass = 'file.class',
  FileComponent = 'file.component',
  FileDirective = 'file.directive',
  FileEnum = 'file.enum',
  FileGuard = 'file.guard',
  FileInterceptor = 'file.interceptor',
  FileInterface = 'file.interface',
  FileModule = 'file.module',
  FilePipe = 'file.pipe',
  FileResolver = 'file.resolver',
  FileService = 'file.service',
  FileSpec = 'file.spec',
  FileTemplate = 'file.template',
  TerminalAnalyticsDisable = 'terminal.analytics.disable',
  TerminalAnalyticsEnable = 'terminal.analytics.enable',
  TerminalAnalyticsInfo = 'terminal.analytics.info',
  TerminalAnalyticsPrompt = 'terminal.analytics.prompt',
  TerminalCacheClear = 'terminal.cache.clear',
  TerminalCacheDisable = 'terminal.cache.disable',
  TerminalCacheEnable = 'terminal.cache.enable',
  TerminalCacheInfo = 'terminal.cache.info',
  TerminalComponent = 'terminal.component',
  TerminalEnvironments = 'terminal.environments',
  TerminalGuard = 'terminal.guard',
  TerminalLibrary = 'terminal.library',
  TerminalPipe = 'terminal.pipe',
  TerminalService = 'terminal.service',
  TerminalStart = 'terminal.start',
  TerminalTest = 'terminal.test',
  TerminalE2E = 'terminal.e2e',
  TerminalVersion = 'terminal.version',
  TerminalNew = 'terminal.new',
  TerminalCustom = 'terminal.custom',
  TransformJsonToTs = 'transform.json.ts',
  ListOpenFile = 'list.openFile',
  ListGotoLine = 'list.gotoLine',
  ListFilesRefresh = 'listFiles.refreshList',
  ListRoutesRefresh = 'listRoutes.refreshList',
  ListModulesRefresh = 'listModules.refreshList',
  FeedbackAboutUs = 'feedback.aboutUs',
  FeedbackReportIssues = 'feedback.reportIssues',
  FeedbackRateUs = 'feedback.rateUs',
  FeedbackSupportUs = 'feedback.supportUs',
}
